
fragment FragmentNodeInterface on NodeInterface {
    __typename
    id
    title
    path
}

fragment FragmentNodePage on NodeInterface {
    ...FragmentNodeInterface
    status
    metatag {
        ...FragmentMetaTag
    }
}

fragment FragmentNodeSupBookAncillary on NodeSupBookAncillary {
    body {
        processed
    }
    supAncillaryBook {
        ...FragmentNodeInterface
        supBookSubtitle
        supBookAuthorsFull
        supBookImage {
            ...FragmentMediaImage
        }

    }
    supAncillaryParagraphs {
        ...FragmentParagraphUnion
    }
}

fragment FragmentNodeSupBook on NodeSupBook {
    supBookAltFormat
    supBookAuthorInfo {
        processed
    }
    supBookAuthors {
        ...FragmentNameType
    }
    supBookAuthorsFull
    supBookAvailDesc
    supBookAwards {
        ...FragmentAward
    }
    supBookCatalogSeasonYyyy
    supBookPublisher
    supBookCopublisherName
    body {
        processed
    }
    supBookDigitalCompLink
    supBookImage {
        ...FragmentMediaImage
    }
    supBookImprint {
        ...FragmentTermInterface
    }
    supBookIsbn13Alt
    supBookIsbn13Cloth
    supBookIsbn13Digital
    supBookIsbn13Isw
    supBookIsbn13Paper
    supBookPages
    supBookPrintDeskCopies
    supBookPubDateCloth {
        ...FragmentDateTime
    }
    supBookPubDateFirst {
        ...FragmentDateTime
    }
    supBookPubYearFirst
    supBookRelatedTitles {
        ...FragmentNodeInterface
    }
    supBookReviews {
        processed
    }
    supBookSalesRank
    supBookSeries {
        ...FragmentTermInterface
        supSeriesPage {
            url
        }
    }
    supBookSubjects {
        __typename
        id
        name
        weight
        parent {
            ... on TermInterface {
                id
                name
            }
        }
    }
    supBookSubtitle
    supBookUrlIsw
    supBookWorkIdNumber
    supBookERetailers {
        ...FragmentLink
    }
    supBookType
    supBookNoCart
    supBookPriceData {
        id
        ... on PressPrice {
            supIntlCart
        }
    }
    supBookEpubFormat
    supBookPdfFormat
}

fragment FragmentNodeStanfordPage on NodeStanfordPage {
    layoutSelection {
        id
    }
    body {
        processed
    }
    suBasicPageType {
        ...FragmentTermInterface
    }
    suPageBanner {
        ...FragmentParagraphStanfordBanner
        ...FragmentParagraphStanfordPageTitleBanner
        ...FragmentParagraphSupCarousel
    }
    suPageComponents {
        ...FragmentParagraphUnion
    }
    suPageDescription
    suPageImage {
        ...FragmentMediaUnion
    }
}

fragment FragmentNodeStanfordCourse on NodeStanfordCourse {
    body {
        processed
    }
    suCourseAcademicYear
    suCourseCode
    suCourseId
    suCourseInstructors
    suCourseLink {
        url
        title
    }
    suCourseQuarters {
        ...FragmentTermInterface
    }
    suCourseSectionUnits
    suCourseSubject {
        ...FragmentTermInterface
    }
    suCourseTags {
        ...FragmentTermInterface
    }
}

fragment FragmentNodeStanfordEvent on NodeStanfordEvent {
    body {
        processed
    }
    suEventAltLoc
    suEventAudience {
        ...FragmentTermInterface
    }
    suEventComponents {
        ...FragmentParagraphUnion
    }
    suEventContactInfo
    suEventCta {
        url
        title
    }
    suEventDateTime {
        ...FragmentSmartDateType
    }
    suEventDek
    suEventEmail
    suEventGroups {
        ...FragmentTermInterface
    }
    suEventKeywords {
        ...FragmentTermInterface
    }
    suEventLocation {
        ...FragmentAddressType
    }
    suEventMapLink {
        url
        title
    }
    suEventSchedule {
        ...FragmentParagraphStanfordSchedule
    }
    suEventSource {
        url
        title
    }
    suEventSponsor
    suEventSubheadline
    suEventSubject {
        ...FragmentTermInterface
    }
    suEventTelephone
    suEventType {
        ...FragmentTermInterface
    }
}

fragment FragmentNodeStanfordEventSeries on NodeStanfordEventSeries {
    suEventSeriesComponents {
        ...FragmentParagraphUnion
    }
    suEventSeriesDek
    suEventSeriesEvent {
        ...FragmentNodeStanfordEventTeaser
    }
    suEventSeriesSubheadline
    suEventSeriesType {
        ...FragmentTermInterface
    }
}

fragment FragmentNodeStanfordNews on NodeStanfordNews {
    suNewsBanner {
        ...FragmentMediaUnion
    }
    suNewsBannerMediaCaption
    suNewsByline
    suNewsComponents {
        ...FragmentParagraphUnion
    }
    suNewsDek
    suNewsFeaturedMedia {
        ...FragmentMediaUnion
    }
    suNewsHideSocial
    suNewsPublishingDate {
        ...FragmentDateTime
    }
    suNewsSource {
        url
        title
    }
    suNewsTopics {
        ...FragmentTermInterface
    }
}

fragment FragmentNodeStanfordPerson on NodeStanfordPerson {
    body {
        processed
    }
    suPersonAcademicAppt
    suPersonAdminAppts
    suPersonAffiliations {
        url
        title
    }
    suPersonComponents {
        ...FragmentParagraphUnion
    }
    suPersonEducation
    suPersonEmail
    suPersonFax
    suPersonFirstName
    suPersonFullTitle
    suPersonLastName
    suPersonLinks {
        url
        title
    }
    suPersonLocationAddress {
        processed
    }
    suPersonLocationName
    suPersonMailCode
    suPersonMapUrl {
        url
        title
    }
    suPersonMobilePhone
    suPersonPhoto {
        ...FragmentMediaImage
    }
    suPersonProfileLink {
        url
        title
    }
    suPersonPronouns
    suPersonResearch {
        processed
    }
    suPersonResearchInterests
    suPersonScholarlyInterests {
        processed
    }
    suPersonShortTitle
    suPersonTelephone
    suPersonTypeGroup {
        ...FragmentTermInterface
    }
}

fragment FragmentNodeStanfordPolicy on NodeStanfordPolicy {
    body {
        processed
    }
    suPolicyAuthority
    suPolicyAutoPrefix
    suPolicyChangelog {
        ...FragmentSuPolicyLog
    }
    suPolicyChapter
    suPolicyEffective {
        ...FragmentDateTime
    }
    suPolicyPolicyNum
    suPolicyRelated {
        ... on NodeInterface {
            id
            path
        }
    }
    suPolicySubchapter
    suPolicyTitle
    suPolicyUpdated {
        ...FragmentDateTime
    }
}

fragment FragmentNodeStanfordPublication on NodeStanfordPublication {
    suPublicationAuthorRef {
        ...FragmentNodeStanfordPersonTeaser
    }
    suPublicationComponents {
        ...FragmentParagraphUnion
    }
    suPublicationCta {
        url
        title
    }
    suPublicationImage {
        ...FragmentMediaImage
    }
    suPublicationTopics {
        ...FragmentTermInterface
    }
}

fragment FragmentNodeUnion on NodeUnion {
    ...FragmentNodePage
    ...FragmentNodeSupBook
    ...FragmentNodeStanfordCourse
    ...FragmentNodeStanfordEvent
    ...FragmentNodeStanfordEventSeries
    ...FragmentNodeStanfordNews
    ...FragmentNodeStanfordPage
    ...FragmentNodeStanfordPerson
    ...FragmentNodeStanfordPolicy
    ...FragmentNodeStanfordPublication
    ...FragmentNodeSupBookAncillary
}

fragment FragmentNodeSupBookTeaser on NodeSupBook {
    ...FragmentNodeInterface
    supBookAuthors {
        ...FragmentNameType
    }
    supBookAwards {
        id
    }
    supBookSubtitle
    supBookWorkIdNumber
    supBookAuthorsFull
    supBookType
    supBookImage {
        ...FragmentMediaImage
    }
}

fragment FragmentNodeStanfordCourseTeaser on NodeStanfordCourse {
    ...FragmentNodeInterface
    suCourseSubject {
        ...FragmentTermInterface
    }
    suCourseAcademicYear
}

fragment FragmentNodeStanfordEventTeaser on NodeStanfordEvent {
    ...FragmentNodeInterface
    suEventAltLoc
    suEventSubheadline
    suEventDek
    suEventLocation {
        ...FragmentAddressType
    }
    suEventDateTime {
        ...FragmentSmartDateType
    }
    suEventType {
        ...FragmentTermInterface
    }
    suEventSource {
        url
        title
    }
}

fragment FragmentNodeStanfordEventSeriesTeaser on NodeStanfordEventSeries {
    ...FragmentNodeInterface
    suEventSeriesDek
}

fragment FragmentNodeStanfordNewsTeaser on NodeStanfordNews {
    ...FragmentNodeInterface
    suNewsDek
    suNewsFeaturedMedia {
        ...FragmentMediaImage
    }
    suNewsTopics {
        ...FragmentTermInterface
    }
    suNewsPublishingDate {
        ...FragmentDateTime
    }
    suNewsSource {
        url
        title
    }
}

fragment FragmentNodeStanfordPageTeaser on NodeStanfordPage {
    ...FragmentNodeInterface
    suPageDescription
    suPageImage {
        ...FragmentMediaImage
    }
    suPageBanner {
        ...FragmentParagraphStanfordBanner
        ...FragmentParagraphStanfordPageTitleBanner
        ...FragmentParagraphSupCarousel
    }
}

fragment FragmentNodeStanfordPersonTeaser on NodeStanfordPerson {
    ...FragmentNodeInterface
    suPersonPhoto {
        ...FragmentMediaImage
    }
    suPersonFullTitle
    suPersonShortTitle
}

fragment FragmentNodeStanfordPolicyTeaser on NodeStanfordPolicy {
    ...FragmentNodeInterface
    body {
        processed
        summary
    }
}

fragment FragmentNodeStanfordPublicationTeaser on NodeStanfordPublication {
    ...FragmentNodeInterface
    suPublicationTopics {
        ...FragmentTermInterface
    }
}

fragment FragmentNodeTeaserUnion on NodeUnion {
    ...FragmentNodeSupBookTeaser
    ...FragmentNodeInterface
    ...FragmentNodeStanfordCourseTeaser
    ...FragmentNodeStanfordEventTeaser
    ...FragmentNodeStanfordEventSeriesTeaser
    ...FragmentNodeStanfordNewsTeaser
    ...FragmentNodeStanfordPageTeaser
    ...FragmentNodeStanfordPersonTeaser
    ...FragmentNodeStanfordPolicyTeaser
    ...FragmentNodeStanfordPublicationTeaser
}

