query BookPrice($id: ID!) {
    press(id: $id) {
        __typename
        ... on PressPrice {
            id
            supAltPrice
            supClothDiscount
            supClothPrice
            supClothSale
            supComingSoon
            supDigitalPrice
            supDigitalSale
            supDigitalDiscount
            supIntlCart
            supPaperDiscount
            supPaperPrice
            supPaperSale
            supPreorder
            workId
        }
    }
}

fragment FragmentAward on PressAward {
    id
    title
    supAssociation
    supDescription {
        processed
    }
    supPlace
    supRank
    supYear
}