query BookPrice($id: ID!) {
    press(id: $id) {
        __typename
        ... on PressPrice {
            id
            supClothPrice
            supClothDiscount
            supClothSale
            supComingSoon
            supDigitalPrice
            supIntlCart
            supPaperPrice
            supPaperDiscount
            supPaperSale
            supPreorder
            workId
        }
    }
}

fragment FragmentAward on PressAward {
    id
    title
    supAssociation
    supDescription {
        processed
    }
    supPlace
    supRank
    supYear
}