
name: Build & Lint
on: [push]
jobs:
  lint:
    name: Lint & TS Check
    runs-on: ubuntu-latest
    container:
      image: node:20
      env:
        NEXT_PUBLIC_DRUPAL_BASE_URL: ${{ secrets.NEXT_PUBLIC_DRUPAL_BASE_URL }}
        DRUPAL_BASIC_AUTH: ${{ secrets.DRUPAL_BASIC_AUTH }}
        DRUPAL_BASIC_AUTH_ADMIN: ${{ secrets.DRUPAL_BASIC_AUTH_ADMIN }}
    steps:
      - uses: actions/checkout@v4
      - name: Restore Cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            .next
          key: 1.x-${{ hashFiles('package.json') }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            1.x-${{ hashFiles('package.json') }}-${{ hashFiles('yarn.lock') }}
            1.x-${{ hashFiles('package.json') }}-
            1.x-
      - name: Lint
        run: |
          yarn
          yarn next telemetry disable
          yarn lint
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: pookmish/drupal8ci:latest
      env:
        BUILD_COMPLETE: 'true'
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: drupal
          MYSQL_USER: drupal
          MYSQL_PASSWORD: drupal
          MYSQL_ROOT_PASSWORD: drupal
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          if_key_exists: fail
      - uses: actions/checkout@v4
        with:
          repository: "SU-SWS/ace-stanfordlagunita"
      - name: Restore Cache
        uses: actions/cache@v4
        with:
          path: |
            vendor
            docroot/core
            docroot/libraries
            docroot/modules/contrib
          key: 2.1-${{ hashFiles('blt/blt.yml') }}-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}
          restore-keys: |
            backend-${{ hashFiles('blt/blt.yml') }}-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}
            backend-${{ hashFiles('blt/blt.yml') }}-${{ hashFiles('composer.json') }}-
            backend-${{ hashFiles('blt/blt.yml') }}-
      - name: Sync Site
        run: |
          git config --system --add safe.directory '*' &&
          mysql -h mysql -P 3306 -u root -pdrupal -e 'SET GLOBAL max_allowed_packet=67108864;' &&
          rm -rf /var/www/html &&
          ln -snf $GITHUB_WORKSPACE /var/www/html &&
          mkdir -p docroot/sites/default/files &&
          chmod -R 777 docroot/sites/default/files/ &&
          rm -rf docroot/sites/supress/files &&
          ln -sL ../default/files/ docroot/sites/supress/files &&
          apachectl stop && apachectl start &&
          composer install -n &&
          blt drupal:sync --site=supress -n
      - uses: actions/checkout@v4
        with:
          path: frontend
      - name: Build Frontend
        run: |
          cd $GITHUB_WORKSPACE/frontend &&
          nvm use &&
          cp .env.example .env.local &&
          sed -i -r "s|NEXT_PUBLIC_DRUPAL_BASE_URL.*|NEXT_PUBLIC_DRUPAL_BASE_URL=http://localhost|g" .env.local &&
          cd $GITHUB_WORKSPACE &&
          drush su-next-connect >> $GITHUB_WORKSPACE/frontend/.env.local &&
          cd $GITHUB_WORKSPACE/frontend &&
          yarn &&
          yarn build